apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-world-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-world-container
            image: bash
            command: ["bash", "-c", "echo 'hello world'"]
          restartPolicy: OnFailure
