apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx_app
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        run: nginx
    spec:
      containers:
        - name: ngx_app
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
